#!/bin/bash

# call ./search WHERE NAME to

SOURCE_DIR="$1"
FILE="$2"

loadFilePath () {
	./search "$SOURCE_DIR" "$FILE"
}

sum="0"
while read -r path ; do
	# i didn't see we could use wc -c FILE but this works too so i left it
	fileSize="$(ls -l "$pwd$path" | grep "$FILE" | sed "s/[[:space:]]\+/ /g" | cut -d " " -f5)"
	sum="$(( sum + fileSize ))"
done < <(loadFilePath) 
echo $sum
